name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'  # Uses latest stable Go version
        cache: true           # Automatically caches Go modules

    - name: Build binary
      run: |
        go build -v -o hm-linux-amd64
        chmod +x hm-linux-amd64
      env:
        CGO_ENABLED: 0
        GOOS: linux
        GOARCH: amd64

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: hm-linux-amd64
        generate_release_notes: true
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
